### ISSUE TITLE
:sparkles: Automated Note Pickup

### ISSUE THREAD

**Issue by liam-teale** [Ten-Ton-Robotics/6364-Crescendo#14]
## Overview
The robot identifies a note in front of it, and moves all necessary subsystems automatically to intake it.

## Motivation
 * Driving the robot to intake a note is hard
 * Notes may move during auto if our alliance partners suck

## Implementation
The LimeLight has object-recognition. However, it needs a Google Coral USB accelerator for this functionality. Fortunately for us, we have both the latest version of the LimeLight and a Google Coral. We can train our own neural network, or use the neural network trained by the kind folks who made the LimeLight (recommended method)

## Todo
- [X] Note is Detected
- [x] LimeLight mounted
- [ ] LimeLight interfaces with the RoboRio over NetworkTables
- [ ] Position info filtered with a Kalman filter (use WPILib tools)
- [ ] Robot moves to the Note
- [ ] Robot intakes the Note

## Additional Information
Team 359 uses this exact same hardware to accomplish this exact same thing, and with great success. This is a path well traveled by others, something we can make use of.
