### ISSUE TITLE
:sparkles: AprilTag Localization with PhotonVision

### ISSUE THREAD

**Issue by liam-teale** [Ten-Ton-Robotics/6364-Crescendo#16]
## Overview
Use PhotonVision for AprilTag detection and localization, along with global shutter cameras. Uses an Orangi Pi 5 for processing.

## Motivation
April Tag detection with the LimeLight is pretty good when the robot is not moving. However, when the robot is moving, which is 99% of the time, performance degrades as the LimeLight uses a rolling shutter camera. We can use a global shutter camera.

## Implementation
2 Global Shutter cameras are mounted to the robot, looking down in front of the robot onto the field. These cameras have line-of-sight of any notes in front of the robot. These 2 cameras are then connected to an Orange Pi 5, which is connected to a network switch, allowing it to interface with the RoboRio. The RoboRio then fuses this data with data with encoder and IMU data.

## Todo
- [x] Wire Orange Pi 5 to buck converter
- [x] Mount Orange Pi 5 to the robot
- [x] Connect global shutter cameras to the Orange Pi 5
- [x] Mount global shutter cameras to the robot
- [x] Orange Pi 5 interfaces with the RoboRio over network tables
- [x] RoboRio fuses data
